### ISSUE TITLE
[Bug]: Add transition effect on version dropdown menu.

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [IridiumIdentity/iridium#175] opened 2023-09-14 07:05 UTC
**Describe the bug**
  The dropdown menu of the version  is to fast. 
Add some transition so that the version will not pop immediately.

**To Reproduce**
1. Go to '.home page..'
2. Click on '.version dropdown option...'
3. See the version dropdown menu pop up very immediately.

**Expected behavior**
The drop-down option of the version will take some millesecond to show option . So , that it will make good user experience.
**Screenshots**
<img width="930" alt="Screenshot 2023-09-14 122850" src="https://github.com/IridiumIdentity/iridium/assets/130988755/eb16f7d4-1337-4828-b00b-e55e6184b584">

**Desktop (please complete the following information):**
 - OS: [e.g. windows 11]
 - Browser [e.g. chrome,]

**Comment by joshfischer1108** [comment] 2023-09-14 16:32
Thanks for reporting this @Rohit-Sharmaa.  Would you be willing to help us with a solution?

**Comment by Rohit-Sharmaa** [comment] 2023-09-15 04:36
@joshfischer1108 yes  i will try to solve and make a pr.

**Comment by fkamau1** [comment] 2023-10-04 12:15
@joshfischer1108 is this issue still open? I would like to work on it.

**Comment by joshfischer1108** [comment] 2023-10-05 12:06
@fkamau1 , the issue is still open. I'll assign it to you if you want it.

Thank you!

**Comment by joshfischer1108** [comment] 2023-10-06 23:36
It's yours.  Thank you!

**Closed** 2023-12-13 02:06 UTC
Labels: bug, good first issue, help wanted, no-issue-activity, hacktoberfest
